export type ResearchPillar =
  | "affective-computing"
  | "act-r-memory"
  | "turn-taking"
  | "edge-middleware"
  | "lifespan-development"

export interface ResearchCitation {
  id: string
  authors: string
  year: number
  title: string
  venue: string
  link: string
  pillar: ResearchPillar
  /** One line on how this specific paper relates to what's actually implemented. */
  relevance: string
}

/**
 * Citations this architecture draws structural inspiration from. Every link below
 * was mechanically checked against its claimed title/authors before publishing --
 * see the methodology note on the Research page. Two entries present in the source
 * bibliography (academic_benchmarks/documentation/literature_references.md, #36 and
 * #37 -- "KnowMeBench" arXiv:2601.07892 and "LMEB" arXiv:2602.09115) were found to
 * resolve to real but entirely unrelated papers and are excluded here.
 */
export const RESEARCH_CITATIONS: ResearchCitation[] = [
  // ── Pillar B: Affective Computing & Appraisal ─────────────────────────────
  {
    id: "mehrabian-1996",
    authors: "Mehrabian, A.",
    year: 1996,
    title: "Pleasure-arousal-dominance: A general framework for describing and measuring individual differences in temperament",
    venue: "Current Psychology",
    link: "https://doi.org/10.1007/BF02686918",
    pillar: "affective-computing",
    relevance: "The 3-dimensional PAD affect space the agent's continuous mood state is represented in, instead of discrete emotion labels.",
  },
  {
    id: "scherer-2005",
    authors: "Scherer, K. R.",
    year: 2005,
    title: "What are emotions? And how can they be measured?",
    venue: "Social Science Information",
    link: "https://doi.org/10.1177/0539018405058216",
    pillar: "affective-computing",
    relevance: "Componential appraisal framing behind mapping affect to observable vocal/behavioral parameters.",
  },
  {
    id: "picard-1997",
    authors: "Picard, R. W.",
    year: 1997,
    title: "Affective Computing",
    venue: "MIT Press",
    link: "https://direct.mit.edu/books/book/2585/Affective-Computing",
    pillar: "affective-computing",
    relevance: "Foundational text for treating emotion as a computational, measurable signal rather than a UI flourish.",
  },
  {
    id: "marsella-gratch-2009",
    authors: "Marsella, S. C. & Gratch, J.",
    year: 2009,
    title: "EMA: A process model of appraisal dynamics",
    venue: "Cognitive Systems Research",
    link: "https://doi.org/10.1016/j.cogsys.2008.03.005",
    pillar: "affective-computing",
    relevance: "Process model for how appraisal of an event updates ongoing affect over time, underlying the appraisal -> PAD update step.",
  },
  {
    id: "becker-asano-wachsmuth-2010",
    authors: "Becker-Asano, C. & Wachsmuth, I.",
    year: 2010,
    title: "Affective computing with primary and secondary emotions in a virtual human",
    venue: "Autonomous Agents and Multi-Agent Systems",
    link: "https://doi.org/10.1007/s10458-009-9094-9",
    pillar: "affective-computing",
    relevance: "Layered primary/secondary emotion architecture informing the tonic (slow) vs. phasic (fast burst) split in the endocrine model.",
  },
  {
    id: "busso-et-al-2008",
    authors: "Busso, C. et al.",
    year: 2008,
    title: "IEMOCAP: Interactive emotional dyadic motion capture database",
    venue: "Language Resources and Evaluation",
    link: "https://doi.org/10.1007/s10579-008-9076-6",
    pillar: "affective-computing",
    relevance: "Reference corpus design for dyadic emotional interaction, relevant background for the affect-labeling pipeline.",
  },
  {
    id: "ringeval-et-al-2013",
    authors: "Ringeval, F., Sonderegger, A., Sauer, J. & Lalanne, D.",
    year: 2013,
    title: "Introducing the RECOLA multimodal corpus of remote collaborative and affective interactions",
    venue: "IEEE International Conference on Automatic Face and Gesture Recognition (FG)",
    link: "https://doi.org/10.1109/FG.2013.6553805",
    pillar: "affective-computing",
    relevance: "Multimodal affective-corpus methodology background for continuous valence/arousal annotation.",
  },

  // ── Pillar C: ACT-R Memory & Hybrid Vector-Graph Retrieval ────────────────
  {
    id: "anderson-et-al-2004",
    authors: "Anderson, J. R., Bothell, D., Byrne, M. D., Douglass, S., Lebiere, C. & Qin, Y.",
    year: 2004,
    title: "An integrated theory of the mind",
    venue: "Psychological Review",
    link: "https://doi.org/10.1037/0033-295X.111.4.1036",
    pillar: "act-r-memory",
    relevance: "The ACT-R base-level activation formula -- ln(recall_count) minus a recency decay term, plus context terms -- is the direct source of the memory-scoring math this system ports almost verbatim.",
  },
  {
    id: "gutierrez-et-al-2024",
    authors: "Gutiérrez, B. J., Shu, Y., Gu, Y., Yasunaga, M. & Su, Y.",
    year: 2024,
    title: "HippoRAG: Neurobiologically Inspired Long-Term Memory for Large Language Models",
    venue: "Advances in Neural Information Processing Systems (NeurIPS 2024)",
    link: "https://arxiv.org/abs/2405.14831",
    pillar: "act-r-memory",
    relevance: "Neurobiologically-inspired long-term memory via graph indexing -- the direct structural precedent for the Neo4j + Personalized PageRank retrieval boost.",
  },
  {
    id: "sumers-et-al-2023",
    authors: "Sumers, T. R., Yao, S., Narasimhan, K. & Griffiths, T. L.",
    year: 2023,
    title: "Cognitive Architectures for Language Agents",
    venue: "Transactions on Machine Learning Research (TMLR)",
    link: "https://arxiv.org/abs/2309.02427",
    pillar: "act-r-memory",
    relevance: "Framework for grounding an LLM-driven agent in classical cognitive-architecture concepts (working/long-term memory, action selection).",
  },
  {
    id: "edge-et-al-2024",
    authors: "Edge, D. et al.",
    year: 2024,
    title: "From Local to Global: A Graph RAG Approach to Query-Focused Summarization",
    venue: "Microsoft Research / arXiv preprint",
    link: "https://arxiv.org/abs/2404.16130",
    pillar: "act-r-memory",
    relevance: "Graph-structured retrieval-augmented generation, background for combining a semantic vector store with a relational graph.",
  },
  {
    id: "lewis-et-al-2020",
    authors: "Lewis, P. et al.",
    year: 2020,
    title: "Retrieval-Augmented Generation for knowledge-intensive NLP tasks",
    venue: "Advances in Neural Information Processing Systems (NeurIPS)",
    link: "https://arxiv.org/abs/2005.11401",
    pillar: "act-r-memory",
    relevance: "The RAG pattern this system's memory retrieval is a specialized, affect-gated instance of.",
  },
  {
    id: "izacard-et-al-2022",
    authors: "Izacard, G. et al.",
    year: 2022,
    title: "Unsupervised dense information retrieval with contrastive learning",
    venue: "Transactions on Machine Learning Research (TMLR)",
    link: "https://arxiv.org/abs/2112.09118",
    pillar: "act-r-memory",
    relevance: "Contrastive dense-retrieval training background for the embedding model used in vector memory search.",
  },
  {
    id: "thakur-et-al-2021",
    authors: "Thakur, N., Reimers, N., Rücklé, A., Srivastava, A. & Gurevych, I.",
    year: 2021,
    title: "BEIR: A heterogeneous benchmark for zero-shot evaluation of information retrieval models",
    venue: "Advances in Neural Information Processing Systems (NeurIPS)",
    link: "https://arxiv.org/abs/2104.08663",
    pillar: "act-r-memory",
    relevance: "Standard reference for evaluating retrieval quality across domains -- methodology context, not a benchmark this project reports against.",
  },
  {
    id: "chen-et-al-2024",
    authors: "Chen, J., Xiao, S., Zhang, P., Luo, K., Lian, D. & Liu, Z.",
    year: 2024,
    title: "M3-Embedding: Multi-Linguality, Multi-Functionality, Multi-Granularity Text Embeddings Through Self-Knowledge Distillation",
    venue: "arXiv preprint",
    link: "https://arxiv.org/abs/2402.03216",
    pillar: "act-r-memory",
    relevance: "Multi-granularity embedding design background relevant to the dynamic-resolution truncation approach used at high cognitive load.",
  },

  // ── Pillar A: Spoken Dialogue Turn-Taking & Interaction Latency ───────────
  {
    id: "skantze-2021",
    authors: "Skantze, G.",
    year: 2021,
    title: "Turn-taking in Conversational Systems and Human-Robot Interaction: A Review",
    venue: "Computer Speech & Language",
    link: "https://doi.org/10.1016/j.csl.2020.101178",
    pillar: "turn-taking",
    relevance: "Survey of turn-taking latency norms in human conversation and human-robot interaction; the ~200ms reference figure for natural turn-gaps.",
  },
  {
    id: "skantze-irfan-2025",
    authors: "Skantze, G. & Irfan, B.",
    year: 2025,
    title: "Applying General Turn-taking Models to Conversational Human-Robot Interaction",
    venue: "ACM/IEEE International Conference on Human-Robot Interaction (HRI)",
    link: "https://arxiv.org/abs/2501.08946",
    pillar: "turn-taking",
    relevance: "Applying general (non-robot-specific) turn-taking models to embodied human-robot interaction, the setting this project targets.",
  },
  {
    id: "ekstedt-skantze-2022",
    authors: "Ekstedt, E. & Skantze, G.",
    year: 2022,
    title: "Voice Activity Projection: Self-supervised Learning of Turn-taking Events",
    venue: "Proceedings of Interspeech",
    link: "https://arxiv.org/abs/2205.09812",
    pillar: "turn-taking",
    relevance: "The Voice Activity Projection concept behind predicting an upcoming turn boundary before the user finishes speaking.",
  },
  {
    id: "ekstedt-skantze-2020",
    authors: "Ekstedt, E. & Skantze, G.",
    year: 2020,
    title: "TurnGPT: a Transformer-based Language Model for Predicting Turn-taking in Spoken Dialogue",
    venue: "Proceedings of Interspeech",
    link: "https://arxiv.org/abs/2010.10874",
    pillar: "turn-taking",
    relevance: "Transformer-based turn-taking prediction, an early precedent for combining linguistic and acoustic signals for turn boundaries.",
  },
  {
    id: "inoue-et-al-2024",
    authors: "Inoue, K., Jiang, B., Ekstedt, E., Kawahara, T. & Skantze, G.",
    year: 2024,
    title: "Multilingual Turn-taking Prediction Using Voice Activity Projection",
    venue: "Proceedings of LREC-COLING",
    link: "https://aclanthology.org/2024.lrec-main.1036/",
    pillar: "turn-taking",
    relevance: "Extends VAP-style turn prediction across languages -- relevant background for a locally-run, language-agnostic pipeline.",
  },
  {
    id: "lala-et-al-2019",
    authors: "Lala, D., Inoue, K. & Kawahara, T.",
    year: 2019,
    title: "Smooth turn-taking by a robot using an online continuous model to generate turn-taking cues",
    venue: "Proceedings of ICMI",
    link: "https://doi.org/10.1145/3340555.3353727",
    pillar: "turn-taking",
    relevance: "Continuous (not just binary) turn-taking cue generation for a robot -- direct precedent for the idle-time proactive-scheduling behavior.",
  },
  {
    id: "raux-eskenazi-2009",
    authors: "Raux, A. & Eskenazi, M.",
    year: 2009,
    title: "A Finite-State Turn-Taking Model for Spoken Dialog Systems",
    venue: "Proceedings of NAACL-HLT",
    link: "https://aclanthology.org/N09-1071/",
    pillar: "turn-taking",
    relevance: "Early finite-state turn-taking model -- the older endpoint-detection approach the VAP-style methods above were built to improve on.",
  },
  {
    id: "kosinski-2023",
    authors: "Kosinski, M.",
    year: 2023,
    title: "Theory of Mind May Have Spontaneously Emerged in Large Language Models",
    venue: "arXiv preprint",
    link: "https://arxiv.org/abs/2302.02083",
    pillar: "turn-taking",
    relevance: "Baseline evidence (and its limits) for LLM Theory-of-Mind performance, the comparison point for this system's separate, deterministic ToM concept-tracker.",
  },

  // ── Pillar D: Edge Middleware, IPC & Local Inference ──────────────────────
  {
    id: "maruyama-et-al-2016",
    authors: "Maruyama, Y., Kato, S. & Azumi, T.",
    year: 2016,
    title: "Exploring the performance of ROS2",
    venue: "Proceedings of the International Conference on Embedded Software (EMSOFT)",
    link: "https://doi.org/10.1145/2968478.2968502",
    pillar: "edge-middleware",
    relevance: "Latency characterization of a DDS-based robotics middleware -- the comparison point for choosing a lighter publish-subscribe layer instead.",
  },
  {
    id: "sharvari-sowmyanag-2019",
    authors: "Sharvari, T. & Sowmya Nag, K.",
    year: 2019,
    title: "A Study on Modern Messaging Systems - Kafka, RabbitMQ and NATS Streaming",
    venue: "arXiv preprint",
    link: "https://arxiv.org/abs/1912.03715",
    pillar: "edge-middleware",
    relevance: "Comparative messaging-system survey informing the choice of NATS JetStream as the inter-agent signal bus.",
  },
  {
    id: "zhang-et-al-2022",
    authors: "Zhang, Y., Zhang, Y., Portokalidis, G. & Xu, J.",
    year: 2022,
    title: "Towards Understanding the Runtime Performance of Rust",
    venue: "Proceedings of ASE",
    link: "https://doi.org/10.1145/3551349.3559494",
    pillar: "edge-middleware",
    relevance: "Empirical basis for using Rust for the latency-critical voice and STT binaries, with a Python control plane atop.",
  },
  {
    id: "prashanthi-et-al-2023",
    authors: "Prashanthi, S. K., Kesanapalli, S. A. & Simmhan, Y.",
    year: 2023,
    title: "Characterizing the Performance of Accelerated Jetson Edge Devices for Training Deep Learning Models",
    venue: "Proceedings of the ACM on Measurement and Analysis of Computing Systems (POMACS) / ACM SIGMETRICS",
    link: "https://arxiv.org/abs/2509.20160",
    pillar: "edge-middleware",
    relevance: "Edge-hardware performance characterization relevant to running the full mesh on constrained local devices.",
  },
  {
    id: "feng-2025",
    authors: "Feng, D.",
    year: 2025,
    title: "Profiling Apple Silicon Performance for ML Training",
    venue: "arXiv preprint",
    link: "https://arxiv.org/abs/2501.14925",
    pillar: "edge-middleware",
    relevance: "Apple Silicon ML performance profiling, directly relevant to running this system's inference locally on macOS hardware.",
  },
  {
    id: "radford-et-al-2023",
    authors: "Radford, A. et al.",
    year: 2023,
    title: "Robust speech recognition via large-scale weak supervision",
    venue: "Proceedings of ICML",
    link: "https://arxiv.org/abs/2212.04356",
    pillar: "edge-middleware",
    relevance: "The Whisper speech-recognition model whose local variants (whisper.cpp) back this system's STT paths.",
  },
  {
    id: "meta-ai-2024",
    authors: "Meta AI",
    year: 2024,
    title: "The Llama 3 Herd of Models",
    venue: "arXiv preprint",
    link: "https://arxiv.org/abs/2407.21783",
    pillar: "edge-middleware",
    relevance: "One of the open-weight local LLM families this system runs against via Ollama.",
  },

  // ── Pillar E: Lifespan Development & Neuromorphic Graph Memory ────────────
  {
    id: "teyler-discenna-1986",
    authors: "Teyler, T. J. & DiScenna, P.",
    year: 1986,
    title: "The hippocampal indexing theory",
    venue: "Behavioral Neuroscience",
    link: "https://doi.org/10.1037/0735-7044.100.2.147",
    pillar: "lifespan-development",
    relevance: "The indexing-theory account of the hippocampus as a pointer structure over cortical memory traces -- the biological metaphor behind graph-indexed episodic memory.",
  },
  {
    id: "mcclelland-et-al-1995",
    authors: "McClelland, J. L., McNaughton, B. L. & O'Reilly, R. C.",
    year: 1995,
    title: "Why there are complementary learning systems in the hippocampus and neocortex: Insights from the successes and failures of connectionist models of learning and memory",
    venue: "Psychological Review",
    link: "https://doi.org/10.1037/0033-295X.102.3.419",
    pillar: "lifespan-development",
    relevance: "Complementary Learning Systems theory -- fast episodic vs. slow consolidated memory -- the direct model for the sleep-cycle consolidation pass.",
  },
  {
    id: "anokhin-et-al-2024",
    authors: "Anokhin, A. et al.",
    year: 2024,
    title: "AriGraph: Learning and Planning in Graph-Based Episodic Memory",
    venue: "arXiv preprint",
    link: "https://arxiv.org/abs/2407.04363",
    pillar: "lifespan-development",
    relevance: "Graph-based episodic memory for planning agents, a contemporary parallel to this system's Neo4j episodic graph.",
  },
  {
    id: "huet-et-al-2025",
    authors: "Huet, A., Ben Houidi, Z. & Rossi, D.",
    year: 2025,
    title: "Episodic Memories Generation and Evaluation Benchmark for Large Language Models",
    venue: "arXiv preprint",
    link: "https://arxiv.org/abs/2501.13121",
    pillar: "lifespan-development",
    relevance: "Benchmark methodology for episodic-memory evaluation -- context for how this project's own Recall@K figures should and shouldn't be compared to published numbers.",
  },
  {
    id: "erikson-erikson-1997",
    authors: "Erikson, E. H. & Erikson, J. M.",
    year: 1997,
    title: "The Life Cycle Completed (Extended Version)",
    venue: "W. W. Norton & Company",
    link: "https://wwnorton.com/books/9780393347432",
    pillar: "lifespan-development",
    relevance: "Psychosocial development-stage theory, background for framing a companion relationship as something that deepens over a real timeline rather than resetting each session.",
  },
]

export const PILLAR_LABELS: Record<ResearchPillar, string> = {
  "affective-computing": "Affective Computing & Appraisal",
  "act-r-memory": "ACT-R Memory & Hybrid Vector-Graph Retrieval",
  "turn-taking": "Turn-Taking & Interaction Latency",
  "edge-middleware": "Edge Middleware & Local Multi-Agent Inference",
  "lifespan-development": "Lifespan Development & Neuromorphic Memory",
}

export const PILLAR_ORDER: ResearchPillar[] = [
  "affective-computing",
  "act-r-memory",
  "turn-taking",
  "edge-middleware",
  "lifespan-development",
]
