name: "🐛 Bug Report"
description: "Report a bug or unexpected behavior in AI Friend"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us squash it.
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "e.g., Pankudi isn't remembering my last session..."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "How can we replicate this issue?"
      placeholder: |
        1. Start the assistant
        2. Say '...'
        3. Observe the result...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      options:
        - Desktop (Windows/Mac/Linux)
        - Mobile (Android/iOS)
        - Docker
        - Other
  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs/Screenshots"
      description: "Please paste any backend logs or attach screenshots if applicable."
