[package]
name = "stt-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
bytes.workspace = true
chrono.workspace = true
contracts.workspace = true
futures-util.workspace = true
hound.workspace = true
reqwest.workspace = true
rubato.workspace = true
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
sherpa-onnx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
whisper-rs.workspace = true
